development: &default
  host: 'http://localhost:9200/'
  transport_options:
    request:
      timeout: !!integer 300

test:
  <<: *default
staging:
  <<: *default

elastic_beanstalk:
  host: <%= ENV['ELASTICSEARCH_URL'] %>
  transport_options:
    request:
      timeout: !!integer 300

production:
  host: <%= ENV['ELASTICSEARCH_URL'] %>
  transport_options:
    request:
      timeout: !!integer 300
